services:
  express-app:
    build: ./express-app
    ports:
      - "3010:3010"
      - "9229:9229"
      - "24678:24678"
    environment:
      PORT: 3010
      FLASK_BACKEND_HOST: flask-app
      FLASK_BACKEND_PORT: 5010
    develop:
      watch:
        - action: sync
          path: ./express-app/app/src/client
          target: /app/src/client
        - action: sync+restart
          path: ./express-app/app/src/server
          target: /app/src/server
        - action: sync+restart
          path: ./express-app/app/index.html
          target: /app/index.html
        - action: rebuild
          path: ./express-app/app/
          include:
            - "*.json"
            - vite.config.ts
            - Dockerfile

  flask-app:
    build: ./flask-app
    ports:
      - "5010:5010"
    environment:
      PORT: 5010
    develop:
      watch:
        - action: sync
          path: ./flask-app
          target: /app
        - action: rebuild
          path: ./flask-app
          include:
            - Dockerfile
            - requirements.txt
