services:
  express-app:
    build: ./express-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
